dothidden/writeups

content/stranger_case/_index.md
- Update our ranking after we got the official results
=> refactor(stranger-case): Update ranking

assets/css/dark.css, assets/css/main.css, config.yaml, content/about/index.md, content/stranger_case/_index.md, layouts/_default/list.html, layouts/_default/term.html, layouts/partials/header.html
* when clicking on a tag you now get a list of all ctfs with that tag and all challenges associated
* no ctfs with 0 challenges are shown
* fix #4
=> BUG: Only show ctf with writeups for tag

config.yaml, layouts/partials/header.html
* basically enabled in config.yaml and cleaned up the header
resolves #19
=> feat: add latex-like syntax support with katex

assets/css/main.css, layouts/index.html
* make text wrap for long lines on mobile
* have the header be overall bigger
=> bigger header & text wrap

archetypes/ctf/_index.md, archetypes/default.md
* now you can just type `hugo new --kind ctf <ctf_name>` to create a new ctf (basically the _index.md file)
* to create a new writeups for a ctf you still use the same command: `hugo new <ctf_name>/<task_name>.md`
resolves issue #31
=> refactor(archetypes): use sepparate templates for different purposes

assets/css/main.css, content/dantectf_2023/_index.md, content/heroctf_v5/_index.md, content/n00bzctf_2023/_index.md, content/pwnme_qualifications_2023/_index.md, content/stranger_case/_index.md, content/umdctf_2023/_index.md, content/unbreakable_2023/_index.md, layouts/_default/list.html, layouts/_default/term.html
- Merged https://github.com/dothidden/writeups/pull/17/commits/278ce0f037bcdd4a75018c4c80f654aa423ecaa9
=> 4 bug tags redirection to not found

content/about/index.md
Opinions on the base64 email? It's a simple way of obfuscating it against the scraper bots and still poses a small challenge for anyone interested.
Is it too much?
=> feat(contact): add contact email in about page

content/codegate_qualifs_2023/_index.md, content/codegate_qualifs_2023/babysandbox.md
=> 49 refactor codegate placement and writeup

content/uiuctf_2023/tornado_warning.md, content/uiuctf_2023/vmware2.md
* two more writeups for this one
=> 48 feat add uiuctf write up

config.yaml, content/balsnctf_2023/Web3.md
Added web3 balsnCtf write up and new member to about list
=> Added web3 BalsnCTF write up and new member to about list

content/cakectf_2023/_index.md, content/cakectf_2023/memorial_cabbage.md
Closes #73 
Waiting on any writeups from @MettleSphee, idk if others have any.
Please create a branch/fork and merge it into this branch with your writeup.
=> Add CakeCTF writeups

content/squarectf_2023/sandbox.md
=> feat(square): add my H0N3YP0T writeups

content/chronosCTF_2024/_index.md
just the index, feel free to add your writeups
=> feat(chronos): add index

content/VishwaCTF_2024/_index.md
Just the index, if you want to add writeups feel free
=> feat(vishwa): add index

content/BackdoorCTF_2023/_index.md
=> feat(backdoorCTF): add index

config.yaml, content/events/index.md
hey bb its me again I made it pretty 💅
approve yes?
=> feat(events): Fill in the event table and prettify

content/unbreakable_2024/finding-god.md, content/unbreakable_2024/just-an-upload.md, content/unbreakable_2024/profile-pic.md, content/unbreakable_2024/sat1sf1.md, content/unbreakable_2024/sums-up.md, content/unbreakable_2024/threat-monitoring.md, content/unbreakable_2024/xfit.md
Closes #109 
I messed up the branch name....
=> fix(unbreakable-2024): Fix minor errors in writeups

content/unbreakable_2024/xfit.md
Just an refactoring of the conclusion text of xfit
=> fix(unbreakable-2024): typo on xfit

content/events/index.md
I forgot to check the ordering......
=> refactor: fix date ordering in events

content/events/index.md
hey babe it's me again
I fucked up the time for Mettle's presentation, put it in the Place column.
tee hee 🤭
=> fix: Fix event table place for Android Modding

content/events/index.md
Guess who's back, back again?
Shady's back, tell a friend
Guess who's back? Guess who's back?
Guess who's back? Guess who's back?
Guess who's back? Guess who's back?
Guess who's back?
(Da-da-da, da, da, da, da, da, da)
(Da-da-da, da, da, da, da)
=> Update place for Symbolic Execution workshop

content/events/index.md
=> feat(events): add OSINT workshop

content/events/index.md
=> update symbolic execution workshop to be in the past

content/unbreakable_2024/harder-assembly.md, content/unbreakable_2024/not-allowed.md, content/unbreakable_2024/sat1sf1.md
I just fixed what was listed. i didn't check for more
=> refactor: fix typos in UBR24 writeups

content/events/index.md
* postpone 15th of may event
* update events' location
* presentation -> workshop for 22nd of may event
=> refactor: event dates and details

config.yaml, content/L3akCTF_2024/_index.md, content/L3akCTF_2024/bbsqli.md, content/L3akCTF_2024/simple_calculator.md
Added myself as member, added l3ak ctf writeups
=> FEAT: Add L3ak CTF writeups

config.yaml, content/HTB_University_2024/MuTLock.md, content/HTB_University_2024/_index.md, content/ekoparty_2023/_index.md, content/umdctf_2024/tcache.md
This PR does two things:
- Fixes site rendering issues due to incompatible changes in the latest versions of Hugo;
- Adds my writeup for the MuTLock challenge from the HTB University 2024 CTF ([rendered](https://github.com/GabrielMajeri/dothidden-writeups/blob/8a5b0e1feda1095dedadaffb4f4b875eff4c5d82/content/HTB_University_2024/MuTLock.md)).
=> Add writeup for MuTLock challenge from HTB University CTF 2024

content/events/index.md
Add new event entry for March seminar
=> add: new event for March

content/Cyber_Apocalypse_CTF_2025/blessing.md, content/Cyber_Apocalypse_CTF_2025/strategist.md
=> docs: add pwn challs

config.yaml, content/Cyber_Apocalypse_CTF_2025/strategist.md
=> add: instagram icon; fix: date for strategist
